# Generated by Django 5.1.2 on 2024-11-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
                ('nickname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('worker', 'Worker')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_duration', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapiapi.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapiapi.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapiapi.project')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='projects',
            field=models.ManyToManyField(through='workflowapiapi.ProjectGroup', to='workflowapiapi.project'),
        ),
        migrations.CreateModel(
            name='ProjectWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapiapi.project')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.CharField(max_length=50)),
                ('projects', models.ManyToManyField(through='workflowapiapi.ProjectWorker', to='workflowapiapi.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflowapiapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='projectworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapiapi.worker'),
        ),
        migrations.CreateModel(
            name='GroupWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapiapi.group')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflowapiapi.worker')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='workers',
            field=models.ManyToManyField(through='workflowapiapi.GroupWorker', to='workflowapiapi.worker'),
        ),
    ]
